<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-10T21:28:25Z" name="Default suite" finished-at="2021-06-10T21:28:30Z" duration-ms="4894">
    <groups>
    </groups>
    <test started-at="2021-06-10T21:28:25Z" name="Default test" finished-at="2021-06-10T21:28:30Z" duration-ms="4894">
      <class name="testsuite.FlightBookingTestSuite">
        <test-method is-config="true" signature="initialize()[pri:0, instance:testsuite.FlightBookingTestSuite@4e423aa2]" started-at="2021-06-10T21:28:20Z" name="initialize" finished-at="2021-06-10T21:28:25Z" duration-ms="5181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:testsuite.FlightBookingTestSuite@4e423aa2]" started-at="2021-06-10T21:28:25Z" name="setUp" finished-at="2021-06-10T21:28:25Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyFlightSearch()[pri:1, instance:testsuite.FlightBookingTestSuite@4e423aa2]" started-at="2021-06-10T21:28:25Z" name="verifyFlightSearch" finished-at="2021-06-10T21:28:27Z" duration-ms="1377" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFlightSearch -->
        <test-method signature="verifyFlightSelect()[pri:2, instance:testsuite.FlightBookingTestSuite@4e423aa2]" started-at="2021-06-10T21:28:27Z" name="verifyFlightSelect" finished-at="2021-06-10T21:28:28Z" duration-ms="1325" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verifying the Details of the selected flight are correct expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verifying the Details of the selected flight are correct expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at testsuite.FlightBookingTestSuite.verifyFlightSelect(FlightBookingTestSuite.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFlightSelect -->
        <test-method signature="verifyFlightBooking()[pri:3, instance:testsuite.FlightBookingTestSuite@4e423aa2]" started-at="2021-06-10T21:28:28Z" name="verifyFlightBooking" finished-at="2021-06-10T21:28:30Z" duration-ms="2119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFlightBooking -->
        <test-method signature="verifyFlightBookingConfirmation()[pri:4, instance:testsuite.FlightBookingTestSuite@4e423aa2]" started-at="2021-06-10T21:28:30Z" name="verifyFlightBookingConfirmation" finished-at="2021-06-10T21:28:30Z" duration-ms="49" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFlightBookingConfirmation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testsuite.FlightBookingTestSuite@4e423aa2]" started-at="2021-06-10T21:28:30Z" name="tearDown" finished-at="2021-06-10T21:28:31Z" duration-ms="680" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testsuite.FlightBookingTestSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
